version: "3.9"
services:
  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/clustreddata
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - clustreddata
    depends_on:
      - psql-db
  psql-db:
    container_name: psql-db
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "clustreddata"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - clustreddata

networks:
  clustreddata:
    driver: bridge

volumes:
  postgres-db:
    driver: local