server:
  port: 8084

spring:
  application:
    name: clusteredData
  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/clustreddata
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
logging:
  level:
    root: INFO
    com.progress.bloomberg: DEBUG
    org.springframework.web: ERROR
